[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[build.environment]
NPM_FLAGS = "--legacy-peer-deps"

[build]
install = "npm install"

[[plugins]]
package = "@netlify/plugin-nextjs"