[build]
  command = "npx prisma generate && next build"
  publish = ".next"
  install = "npm install"

[build.environment]
NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
package = "@netlify/plugin-nextjs"